// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.nat.changer.domain;

import net.nat.changer.domain.Change;

privileged aspect Change_Roo_JavaBean {
    
    public String Change.getDescription() {
        return this.description;
    }
    
    public void Change.setDescription(String description) {
        this.description = description;
    }
    
}
