// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.nat.changer.domain;

import java.io.Serializable;
import net.nat.changer.domain.Change;

privileged aspect Change_Roo_Serializable {
    
    declare parents: Change implements Serializable;
    
    private static final long Change.serialVersionUID = 1L;
    
}
